# Generated by Django 2.2.5 on 2019-09-24 02:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(max_length=200, verbose_name='是由')),
                ('Amount', models.CharField(max_length=200, verbose_name='数额')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('FinanceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinanceType', verbose_name='记账类名')),
            ],
            options={
                'verbose_name': '记账记录',
                'verbose_name_plural': '记账记录',
            },
        ),
    ]
