# Generated by Django 2.2.5 on 2019-09-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='itResult',
            field=models.IntegerField(default=0, verbose_name='整型应答'),
        ),
        migrations.AlterField(
            model_name='config',
            name='stResult',
            field=models.CharField(default='', max_length=200, verbose_name='字符串应答'),
        ),
    ]
